# Generated by Django 6.0.3 on 2026-03-10 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('GP', 'General Practitioner'), ('CARD', 'Cardiologist'), ('DERM', 'Dermatologist'), ('ENDO', 'Endocrinologist'), ('GAST', 'Gastroenterologist'), ('NEPH', 'Nephrologist'), ('NEUR', 'Neurologist'), ('ONCO', 'Oncologist'), ('OPHT', 'Ophthalmologist'), ('ORTH', 'Orthopedic Surgeon'), ('PATH', 'Pathologist'), ('PED', 'Pediatrician'), ('PSYC', 'Psychiatrist'), ('RAD', 'Radiologist'), ('SURG', 'Surgeon'), ('UROL', 'Urologist')], max_length=4)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('office_address', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(help_text='e.g., Monday, Tuesday, Wednesday', max_length=100)),
                ('available_time_start', models.TimeField()),
                ('available_time_end', models.TimeField()),
                ('bio', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
